name = "github-to-pages"
compatibility_date = "2023-12-01"

[build]
command = ""
upload.format = "directory"

[site]
bucket = "./public"

# 默认路由
[[routes]]
pattern = "/*"
script = "functions/[[path]].js"

[[routes]]
pattern = "/api/upload/create-session"
script = "functions/api/upload.js"

[[routes]]
pattern = "/api/upload/chunk"
script = "functions/api/upload.js"

[[routes]]
pattern = "/api/upload/complete"
script = "functions/api/upload.js"

[[routes]]
pattern = "/api/upload/cancel"
script = "functions/api/upload.js"

[[routes]]
pattern = "/api/upload"
script = "functions/api/upload.js"

[[routes]]
pattern = "/api/*"
script = "functions/api/[[path]].js"

[[routes]]
pattern = "/admin/*"
script = "functions/admin/[[path]].js" 
